django/apps/polls/urls.py
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'polls'

urlpatterns = [
    # 画面
    # トップ画面
    path('', views.IndexView.as_view(), name='index'),
    # 投票画面
    path('vote/<int:pk>/', views.VoteView.as_view(), name='vote'),
    # 再投票
    path('revote/<int:pk>/', views.RevoteView.as_view(), name='revote'),
    # 更新履歴
    path('update_history/', views.UpdateHistory, name='update_history'),
    # 構成図
    path('diagram/', views.Diagram, name='diagram'),
    # 質問作成
    path('create_question/', views.CreateQuestion.as_view() , name='create_question'),
    # コメント投稿
    path('post_comment/<int:pk>/', views.PostComment.as_view() , name='post_comment'),

    # 新規登録
    path('register', views.AccountRegistration.as_view(), name='register'),
    # ログイン
    path('login/',views.Login,name='login'),
    # ログアウト
    path("logout/",views.Logout,name="logout"),
    # ゲストログイン
    path('guest_login/', views.guest_login, name = 'guest_login'), #かんたんログイン用
    # 個人トップ画面
    path('<str:username>/account_top/', views.AccountTop.as_view(), name='account_top'),
    # 個人情報
    path('<str:username>/account_info', views.AccountInfo.as_view(), name='account_info'),

    # API
    path('api/questions/', views.QuestionListAPIView.as_view()),
    path('api/questions/<int:pk>/', views.QuestionRetrieveAPIView.as_view()),
    path('api/choices/<int:pk>/', views.ChoiceListAPIView.as_view()),
    path('api/comments/<int:pk>/', views.CommentListAPIView.as_view()),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/polls/urls.py
from . import apis
from .apis import (
    VoteViewSet,
    CommentViewSet,
    QuestionViewSet,
    ChoiceViewSet,
    UserViewSet,
    UpdateContentViewSet,
)
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers

defaultRouter = routers.DefaultRouter()
defaultRouter.register("user", UserViewSet)
defaultRouter.register("vote", VoteViewSet)
defaultRouter.register("comment", CommentViewSet)
defaultRouter.register("question", QuestionViewSet)
defaultRouter.register("choice", ChoiceViewSet)
defaultRouter.register("update_content", UpdateContentViewSet)

app_name = "polls"

urlpatterns = [
    # ログイン
    path("api/login/", apis.do_login),
    # Googleログイン
    path("api/google_login/", apis.google_login),
    # ログアウト
    path("api/logout/", apis.do_logout),
    # アカウント仮登録
    path("api/account_register/", apis.account_register),
    # アカウント本登録
    path("api/account_register_complete/", apis.account_register_complete),
    # パスワード再設定メール送信
    path("api/password_reset_mail/", apis.password_reset_mail),
    # パスワード再設定
    path("api/password_reset/", apis.password_reset),
    # ユーザ名変更
    path("api/update_username/", apis.update_username),
    # パスワード変更
    path("api/update_password/", apis.update_password),
    # api/に各CRUDエンドポイントを作成
    path("api/", include(defaultRouter.urls)),
    # ユーザ情報取得
    path("api/get_user_info/", apis.get_user_info),
    # 質問作成
    path("api/create_question/", apis.create_question),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/templates/accounts/login.html
{% extends 'base.html' %}
{% block extra-static %}
{% load static %}
<link rel="stylesheet" href='{% static "accounts/css/login.css" %}'/>
{% endblock %}
{% block title %}ログイン{% endblock %}

{% block content %}
  <form method="post" action="{% url 'accounts:Login' %}">
    {% csrf_token %}
    <div id="container" class="container container-fluid">
       <div class="row">
         <div class="col-sm-4">
            <label for="userid">ユーザーID:</label>
         </div>
         <div class="col-sm-8">
            <input type="text" name="userid" required> 
        </div>
      </div>
      <div class="row">
         <div class="col-sm-4">
            <label for="password">パスワード：</label>
         </div>
         <div class="col-sm-8">
            <input type="password" name="password" required>
         </div>
      </div>
       <div class="row">
         <div class="col-sm-4">
         </div>
         <div class="col-sm-8">
            <input type="submit" class="btn" value="ログイン">
         </div>
       </div>
       <div class="row">
          <div class="col-sm-12"><a href="{% url 'polls:register' %}">アカウントを作成</a></div>
         </div>
         <div class="row">
          <div class="col-sm-12"><a href="{% url 'accounts:guest_login' %}">ゲストログイン</a></div>
       </div>
    </div>

    
 </form>
   
{% endblock %}